# {
#   "useTabs": false,
#   "printWidth": 80,
#   "tabWidth": 2,
#   "singleQuote": true,
#   "trailingComma": "none",
#   "jsxBracketSameLine": false
# }
useTabs: false
tabWidth: 2
singleQuote: true
trailingComma: none
